apiVersion: console.openshift.io/v1
kind: ConsoleYAMLSample
metadata:
  name: 2-resource-4-pvc2
spec:
  description: PersistentVolumeClaim
  targetResource:
    apiVersion: v1
    kind: PersistentVolumeClaim
  title: 2-resource-4-pvc2
  yaml: |
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: 2-resource-4-pvc2
      namespace: resource-quota
    spec:
      accessModes:
        - ReadWriteOnce
      volumeMode: Filesystem
      resources:
        requests:
          storage: 1Gi
